DROP TABLE Account;
DROP TABLE Profile;
DROP TABLE Topic;
DROP DOMAIN GENDER;
DROP DOMAIN RATING;

CREATE DOMAIN GENDER as VARCHAR CHECK(
  VALUE = 'M' OR VALUE  = 'F'
);

CREATE DOMAIN RATING as DECIMAL(3,1) CHECK(
  VALUE <= 10 AND VALUE >= 0
);


CREATE TABLE Account (
  Account_ID SERIAL NOT NULL PRIMARY KEY,
  Password VARCHAR(40) NOT NULL,
  Salt VARCHAR(8) NOT NULL,
  Username VARCHAR(32) NOT NULL,
  Email VARCHAR(255) NOT NULL
);

CREATE TABLE Profile (
  Profile_ID SERIAL NOT NULL PRIMARY KEY,
  Account_ID INT NOT NULL REFERENCES Account(Account_ID),
  First_Name VARCHAR(32),
  Last_Name VARCHAR(32),
  DOB DATE,
  Gender GENDER,
  Occupation VARCHAR(64),
  Device_Used VARCHAR(64)
);

CREATE TABLE Topic (
  Topic_ID SERIAL NOT NULL PRIMARY KEY,
  Description VARCHAR(64) NOT NULL
);

CREATE TABLE Movie (
  Movie_ID SERIAL NOT NULL PRIMARY KEY,
  Title VARCHAR(64) NOT NULL,
  Date_Released DATE NOT NULL,
  Description TEXT NOT NULL,
  Rating RATING NOT NULL
);

CREATE TABLE Watches (
  Profile_ID INT NOT NULL REFERENCES Profile(Profile_ID),
  Movie_ID INT NOT NULL REFERENCES Movie(Movie_ID),
  Date DATE NOT NULL,
  Rating RATING NOT NULL
);

CREATE TABLE MovieTopics (
  Movie_ID INT NOT NULL REFERENCES Movie(Movie_ID),
  Topic_ID INT NOT NULL REFERENCES Topic(Topic_ID),
  CONSTRAINT pk_Movie_Topics PRIMARY KEY (Movie_ID, Topic_ID)
);

CREATE TABLE Actor (
  Actor_ID SERIAL NOT NULL PRIMARY KEY,
  First_Name VARCHAR(64) NOT NULL PRIMARY KEY,
  Last_Name VARCHAR(64) NOT NULL PRIMARY KEY,
  DOB DATE NOT NULL
);

CREATE TABLE Role (
  Role_ID SERIAL NOT NULL PRIMARY KEY,
  Name VARCHAR(64) NOT NULL,
  Actor_ID INT NOT NULL REFERENCES Actor(Actor_ID)
);

CREATE TABLE MovieActor (
  Movie_ID INT NOT NULL REFERENCES Movie(Movie_ID),
  Actor_ID INT NOT NULL REFERENCES Actor(Actor_ID),
  CONSTRAINT pk_Movie_Actor PRIMARY KEY (Movie_ID, Actor_ID)
);

CREATE TABLE Director (
  Director_ID SERIAL NOT NULL PRIMARY KEY,
  First_Name VARCHAR(64) NOT NULL PRIMARY KEY,
  Last_Name VARCHAR(64) NOT NULL PRIMARY KEY,
  DOB DATE NOT NULL
);

CREATE TABLE MovieDirector (
  Movie_ID INT NOT NULL REFERENCES Movie(Movie_ID),
  Director_ID INT NOT NULL REFERENCES Director(Director_ID),
  CONSTRAINT pk_Movie_Director PRIMARY KEY (Movie_ID, Director_ID)
);

CREATE TABLE Studio (
  Studio_ID SERIAL NOT NULL PRIMARY KEY,
  Name VARCHAR(64) NOT NULL,
  Country VARCHAR(64) NOT NULL
);

CREATE TABLE MovieDirector (
  Movie_ID INT NOT NULL REFERENCES Movie(Movie_ID),
  Director_ID INT NOT NULL REFERENCES Director(Director_ID),
  CONSTRAINT pk_Movie_Director PRIMARY KEY (Movie_ID, Director_ID)
);